version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lead-management-api
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - GIN_MODE=release
    volumes:
      - ./data:/root/data
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8001/clients"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 